[rospy.client][INFO] 2021-12-14 10:39:12,775: init_node, name[/server_endpoint], pid[19187]
[xmlrpc][INFO] 2021-12-14 10:39:12,776: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-14 10:39:12,776: Started XML-RPC server [http://wng:34935/]
[rospy.init][INFO] 2021-12-14 10:39:12,776: ROS Slave URI: [http://wng:34935/]
[rospy.impl.masterslave][INFO] 2021-12-14 10:39:12,776: _ready: http://wng:34935/
[xmlrpc][INFO] 2021-12-14 10:39:12,777: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-14 10:39:12,777: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-12-14 10:39:12,876: registered with master
[rospy.rosout][INFO] 2021-12-14 10:39:12,877: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-14 10:39:12,878: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-14 10:39:12,878: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-14 10:39:12,884: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-14 10:39:13,161: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-14 10:40:25,563: Connection from 192.168.0.8
[rosout][INFO] 2021-12-14 10:40:25,567: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-14 10:40:25,675: topic[/execution_check] adding connection to [http://wng:34935/], count 0
[rospy.internal][INFO] 2021-12-14 10:40:25,676: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rosout][ERROR] 2021-12-14 10:41:25,399: Exception: No more data available
[rosout][INFO] 2021-12-14 10:41:25,400: Disconnected from 192.168.0.8
[rospy.core][INFO] 2021-12-14 10:41:33,216: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-14 10:41:33,223: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-14 10:41:33,224: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-14 10:41:33,224: topic[/execution_check] removing connection to http://wng:34935/
[rospy.impl.masterslave][INFO] 2021-12-14 10:41:33,224: signal-2
[rospy.internal][ERROR] 2021-12-14 10:41:33,225: Unable to initiate TCP/IP socket to wng:36789 (http://wng:34935/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-12-14 10:41:33,325: signal_shutdown [atexit]
