[rospy.client][INFO] 2021-09-18 23:13:33,900: init_node, name[/server_endpoint], pid[15499]
[xmlrpc][INFO] 2021-09-18 23:13:33,901: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-09-18 23:13:33,901: Started XML-RPC server [http://wng:33503/]
[rospy.impl.masterslave][INFO] 2021-09-18 23:13:33,901: _ready: http://wng:33503/
[rospy.init][INFO] 2021-09-18 23:13:33,901: ROS Slave URI: [http://wng:33503/]
[rospy.registration][INFO] 2021-09-18 23:13:33,901: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-09-18 23:13:33,901: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-09-18 23:13:34,001: registered with master
[rospy.rosout][INFO] 2021-09-18 23:13:34,002: initializing /rosout core topic
[rospy.rosout][INFO] 2021-09-18 23:13:34,003: connected to core topic /rosout
[rospy.simtime][INFO] 2021-09-18 23:13:34,004: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-09-18 23:13:34,013: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-09-18 23:13:34,266: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-09-18 23:13:51,862: Connection from 192.168.1.146
[rosout][INFO] 2021-09-18 23:13:51,866: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-09-18 23:13:51,938: topic[/execution_check] adding connection to [http://wng:33503/], count 0
[rospy.internal][INFO] 2021-09-18 23:13:51,939: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-09-18 23:37:31,007: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-09-18 23:37:31,011: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-09-18 23:37:31,011: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-09-18 23:37:31,012: topic[/execution_check] removing connection to http://wng:33503/
[rospy.impl.masterslave][INFO] 2021-09-18 23:37:31,012: signal-2
[rospy.internal][ERROR] 2021-09-18 23:37:31,012: Unable to initiate TCP/IP socket to wng:41091 (http://wng:33503/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-09-18 23:37:31,143: signal_shutdown [atexit]
