[rospy.client][INFO] 2021-12-14 10:21:21,066: init_node, name[/server_endpoint], pid[15893]
[xmlrpc][INFO] 2021-12-14 10:21:21,067: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-14 10:21:21,067: Started XML-RPC server [http://wng:45307/]
[rospy.init][INFO] 2021-12-14 10:21:21,067: ROS Slave URI: [http://wng:45307/]
[rospy.impl.masterslave][INFO] 2021-12-14 10:21:21,067: _ready: http://wng:45307/
[xmlrpc][INFO] 2021-12-14 10:21:21,068: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-14 10:21:21,068: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-12-14 10:21:21,168: registered with master
[rospy.rosout][INFO] 2021-12-14 10:21:21,168: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-14 10:21:21,169: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-14 10:21:21,170: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-14 10:21:21,175: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-14 10:21:21,382: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-14 10:21:22,169: Connection from 192.168.0.8
[rosout][ERROR] 2021-12-14 10:21:23,197: Exception: No more data available
[rosout][INFO] 2021-12-14 10:21:23,198: Disconnected from 192.168.0.8
[rosout][INFO] 2021-12-14 10:21:42,036: Connection from 192.168.0.8
[rosout][INFO] 2021-12-14 10:21:42,040: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-14 10:21:42,153: topic[/execution_check] adding connection to [http://wng:45307/], count 0
[rospy.internal][INFO] 2021-12-14 10:21:42,154: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-14 10:23:53,167: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-14 10:23:53,171: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-14 10:23:53,172: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-14 10:23:53,172: topic[/execution_check] removing connection to http://wng:45307/
[rospy.impl.masterslave][INFO] 2021-12-14 10:23:53,172: signal-2
[rospy.internal][ERROR] 2021-12-14 10:23:53,172: Unable to initiate TCP/IP socket to wng:38333 (http://wng:45307/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-12-14 10:23:53,304: signal_shutdown [atexit]
