[rospy.client][INFO] 2021-09-24 14:30:30,539: init_node, name[/server_endpoint], pid[24620]
[xmlrpc][INFO] 2021-09-24 14:30:30,540: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-09-24 14:30:30,540: Started XML-RPC server [http://wng:39525/]
[rospy.init][INFO] 2021-09-24 14:30:30,540: ROS Slave URI: [http://wng:39525/]
[rospy.impl.masterslave][INFO] 2021-09-24 14:30:30,540: _ready: http://wng:39525/
[rospy.registration][INFO] 2021-09-24 14:30:30,540: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-09-24 14:30:30,540: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-09-24 14:30:30,640: registered with master
[rospy.rosout][INFO] 2021-09-24 14:30:30,641: initializing /rosout core topic
[rospy.rosout][INFO] 2021-09-24 14:30:30,642: connected to core topic /rosout
[rospy.simtime][INFO] 2021-09-24 14:30:30,642: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-09-24 14:30:30,650: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-09-24 14:30:30,904: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-09-24 14:30:56,838: Connection from 192.168.1.146
[rosout][INFO] 2021-09-24 14:30:56,843: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-09-24 14:30:56,884: topic[/execution_check] adding connection to [http://wng:39525/], count 0
[rospy.internal][INFO] 2021-09-24 14:30:56,885: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rosout][ERROR] 2021-09-24 15:02:10,113: Exception: No more data available
[rosout][INFO] 2021-09-24 15:02:10,115: Disconnected from 192.168.1.146
[rospy.core][INFO] 2021-09-24 15:02:59,838: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-09-24 15:02:59,842: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-09-24 15:02:59,842: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-09-24 15:02:59,842: topic[/execution_check] removing connection to http://wng:39525/
[rospy.impl.masterslave][INFO] 2021-09-24 15:02:59,842: signal-2
[rospy.internal][ERROR] 2021-09-24 15:02:59,843: Unable to initiate TCP/IP socket to wng:33441 (http://wng:39525/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-09-24 15:03:00,457: signal_shutdown [atexit]
