[rospy.client][INFO] 2021-12-10 09:10:37,305: init_node, name[/server_endpoint], pid[14613]
[xmlrpc][INFO] 2021-12-10 09:10:37,305: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-10 09:10:37,305: Started XML-RPC server [http://wng:38875/]
[rospy.init][INFO] 2021-12-10 09:10:37,305: ROS Slave URI: [http://wng:38875/]
[rospy.impl.masterslave][INFO] 2021-12-10 09:10:37,306: _ready: http://wng:38875/
[xmlrpc][INFO] 2021-12-10 09:10:37,306: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-10 09:10:37,306: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-12-10 09:10:37,406: registered with master
[rospy.rosout][INFO] 2021-12-10 09:10:37,406: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-10 09:10:37,407: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-10 09:10:37,408: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-10 09:10:37,414: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-10 09:10:37,706: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-10 09:10:44,697: Connection from 192.168.0.8
[rosout][INFO] 2021-12-10 09:10:44,702: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-10 09:10:44,736: topic[/execution_check] adding connection to [http://wng:38875/], count 0
[rospy.internal][INFO] 2021-12-10 09:10:44,739: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-10 09:31:15,936: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-10 09:31:15,942: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-10 09:31:15,942: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-10 09:31:15,942: topic[/execution_check] removing connection to http://wng:38875/
[rospy.impl.masterslave][INFO] 2021-12-10 09:31:15,942: signal-2
[rospy.internal][WARNING] 2021-12-10 09:31:15,943: Unknown error initiating TCP/IP socket to wng:41073 (http://wng:38875/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 561, in connect
    self.write_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 642, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 417, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe

[rospy.core][INFO] 2021-12-10 09:31:16,046: signal_shutdown [atexit]
