[rospy.client][INFO] 2021-11-29 09:13:40,334: init_node, name[/server_endpoint], pid[5857]
[xmlrpc][INFO] 2021-11-29 09:13:40,335: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-11-29 09:13:40,335: Started XML-RPC server [http://wng:36275/]
[rospy.init][INFO] 2021-11-29 09:13:40,335: ROS Slave URI: [http://wng:36275/]
[rospy.impl.masterslave][INFO] 2021-11-29 09:13:40,335: _ready: http://wng:36275/
[xmlrpc][INFO] 2021-11-29 09:13:40,336: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-11-29 09:13:40,336: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-11-29 09:13:40,436: registered with master
[rospy.rosout][INFO] 2021-11-29 09:13:40,436: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-29 09:13:40,437: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-29 09:13:40,437: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-11-29 09:13:40,441: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-11-29 09:13:40,716: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-11-29 09:13:51,970: Connection from 192.168.1.146
[rosout][INFO] 2021-11-29 09:13:51,974: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-11-29 09:13:52,069: topic[/execution_check] adding connection to [http://wng:36275/], count 0
[rospy.internal][INFO] 2021-11-29 09:13:52,070: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-11-29 09:32:18,951: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-11-29 09:32:18,954: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][ERROR] 2021-11-29 09:32:18,954: Unable to initiate TCP/IP socket to wng:36585 (http://wng:36275/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2021-11-29 09:32:18,955: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-11-29 09:32:18,955: topic[/execution_check] removing connection to http://wng:36275/
[rospy.impl.masterslave][INFO] 2021-11-29 09:32:18,955: signal-2
[rospy.core][INFO] 2021-11-29 09:32:19,119: signal_shutdown [atexit]
