[rospy.client][INFO] 2021-09-06 15:25:07,504: init_node, name[/server_endpoint], pid[26798]
[xmlrpc][INFO] 2021-09-06 15:25:07,505: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-09-06 15:25:07,505: Started XML-RPC server [http://wng:35889/]
[rospy.impl.masterslave][INFO] 2021-09-06 15:25:07,505: _ready: http://wng:35889/
[rospy.init][INFO] 2021-09-06 15:25:07,505: ROS Slave URI: [http://wng:35889/]
[rospy.registration][INFO] 2021-09-06 15:25:07,505: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-09-06 15:25:07,505: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-09-06 15:25:07,606: registered with master
[rospy.rosout][INFO] 2021-09-06 15:25:07,606: initializing /rosout core topic
[rospy.rosout][INFO] 2021-09-06 15:25:07,609: connected to core topic /rosout
[rospy.simtime][INFO] 2021-09-06 15:25:07,611: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-09-06 15:25:07,632: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-09-06 15:25:07,836: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-09-06 15:25:37,610: Connection from 192.168.1.146
[rosout][INFO] 2021-09-06 15:25:37,614: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-09-06 15:25:37,646: topic[/execution_check] adding connection to [http://wng:35889/], count 0
[rospy.internal][INFO] 2021-09-06 15:25:37,648: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rosout][ERROR] 2021-09-06 15:33:38,755: Exception: No more data available
[rosout][INFO] 2021-09-06 15:33:38,757: Disconnected from 192.168.1.146
[rospy.core][INFO] 2021-09-06 15:35:38,438: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-09-06 15:35:38,442: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-09-06 15:35:38,443: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-09-06 15:35:38,443: topic[/execution_check] removing connection to http://wng:35889/
[rospy.impl.masterslave][INFO] 2021-09-06 15:35:38,443: signal-2
[rospy.internal][ERROR] 2021-09-06 15:35:38,443: Unable to initiate TCP/IP socket to wng:45731 (http://wng:35889/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-09-06 15:35:38,547: signal_shutdown [atexit]
