[rospy.client][INFO] 2021-12-09 17:27:21,893: init_node, name[/server_endpoint], pid[10965]
[xmlrpc][INFO] 2021-12-09 17:27:21,894: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-09 17:27:21,894: Started XML-RPC server [http://wng:40999/]
[rospy.init][INFO] 2021-12-09 17:27:21,895: ROS Slave URI: [http://wng:40999/]
[rospy.impl.masterslave][INFO] 2021-12-09 17:27:21,895: _ready: http://wng:40999/
[rospy.registration][INFO] 2021-12-09 17:27:21,895: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-12-09 17:27:21,895: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-09 17:27:21,995: registered with master
[rospy.rosout][INFO] 2021-12-09 17:27:21,995: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-09 17:27:21,996: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-09 17:27:21,997: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-09 17:27:22,002: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-09 17:27:22,282: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-09 17:27:28,693: Connection from 192.168.0.8
[rosout][INFO] 2021-12-09 17:27:28,700: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-09 17:27:28,827: topic[/execution_check] adding connection to [http://wng:40999/], count 0
[rospy.internal][INFO] 2021-12-09 17:27:28,828: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-09 17:49:07,846: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-09 17:49:07,852: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-09 17:49:07,852: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-09 17:49:07,853: topic[/execution_check] removing connection to http://wng:40999/
[rospy.impl.masterslave][INFO] 2021-12-09 17:49:07,853: signal-2
[rospy.internal][WARNING] 2021-12-09 17:49:07,854: Unknown error initiating TCP/IP socket to wng:39805 (http://wng:40999/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 561, in connect
    self.write_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 642, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 417, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe

[rospy.core][INFO] 2021-12-09 17:49:08,468: signal_shutdown [atexit]
