[rospy.client][INFO] 2021-11-26 08:33:05,433: init_node, name[/server_endpoint], pid[27904]
[xmlrpc][INFO] 2021-11-26 08:33:05,433: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2021-11-26 08:33:05,433: ROS Slave URI: [http://wng:36737/]
[xmlrpc][INFO] 2021-11-26 08:33:05,433: Started XML-RPC server [http://wng:36737/]
[rospy.impl.masterslave][INFO] 2021-11-26 08:33:05,433: _ready: http://wng:36737/
[rospy.registration][INFO] 2021-11-26 08:33:05,433: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-11-26 08:33:05,434: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-11-26 08:33:05,534: registered with master
[rospy.rosout][INFO] 2021-11-26 08:33:05,534: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-26 08:33:05,537: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-26 08:33:05,540: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-11-26 08:33:05,558: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-11-26 08:33:05,747: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-11-26 08:33:31,107: Connection from 192.168.1.146
[rosout][INFO] 2021-11-26 08:33:31,112: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-11-26 08:33:31,123: topic[/execution_check] adding connection to [http://wng:36737/], count 0
[rospy.internal][INFO] 2021-11-26 08:33:31,128: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-11-26 09:09:21,826: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-11-26 09:09:21,829: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-11-26 09:09:21,829: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-11-26 09:09:21,829: topic[/execution_check] removing connection to http://wng:36737/
[rospy.impl.masterslave][INFO] 2021-11-26 09:09:21,830: signal-2
[rospy.internal][ERROR] 2021-11-26 09:09:21,830: Unable to initiate TCP/IP socket to wng:45949 (http://wng:36737/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-11-26 09:09:21,961: signal_shutdown [atexit]
