[rospy.client][INFO] 2021-12-01 15:21:18,891: init_node, name[/server_endpoint], pid[6684]
[xmlrpc][INFO] 2021-12-01 15:21:18,891: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-01 15:21:18,892: Started XML-RPC server [http://wng:39755/]
[rospy.init][INFO] 2021-12-01 15:21:18,892: ROS Slave URI: [http://wng:39755/]
[rospy.impl.masterslave][INFO] 2021-12-01 15:21:18,892: _ready: http://wng:39755/
[rospy.registration][INFO] 2021-12-01 15:21:18,893: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-12-01 15:21:18,893: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-01 15:21:18,992: registered with master
[rospy.rosout][INFO] 2021-12-01 15:21:18,993: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-01 15:21:18,994: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-01 15:21:18,995: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-01 15:21:19,000: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-01 15:21:19,257: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-01 15:21:25,441: Connection from 192.168.0.8
[rosout][INFO] 2021-12-01 15:21:25,446: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-01 15:21:25,473: topic[/execution_check] adding connection to [http://wng:39755/], count 0
[rospy.internal][INFO] 2021-12-01 15:21:25,475: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-01 15:41:37,282: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-01 15:41:37,287: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-01 15:41:37,287: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-01 15:41:37,287: topic[/execution_check] removing connection to http://wng:39755/
[rospy.impl.masterslave][INFO] 2021-12-01 15:41:37,288: signal-2
[rospy.internal][ERROR] 2021-12-01 15:41:37,288: Unable to initiate TCP/IP socket to wng:43487 (http://wng:39755/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-12-01 15:41:37,419: signal_shutdown [atexit]
