[rospy.client][INFO] 2021-11-24 16:43:38,896: init_node, name[/server_endpoint], pid[18101]
[xmlrpc][INFO] 2021-11-24 16:43:38,897: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-11-24 16:43:38,897: Started XML-RPC server [http://wng:38503/]
[rospy.impl.masterslave][INFO] 2021-11-24 16:43:38,897: _ready: http://wng:38503/
[rospy.init][INFO] 2021-11-24 16:43:38,897: ROS Slave URI: [http://wng:38503/]
[xmlrpc][INFO] 2021-11-24 16:43:38,897: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-11-24 16:43:38,897: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-11-24 16:43:38,997: registered with master
[rospy.rosout][INFO] 2021-11-24 16:43:38,998: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-24 16:43:38,998: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-24 16:43:38,999: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-11-24 16:43:39,003: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-11-24 16:43:39,185: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-11-24 16:43:53,224: Connection from 192.168.1.146
[rosout][INFO] 2021-11-24 16:43:53,228: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-11-24 16:43:53,280: topic[/execution_check] adding connection to [http://wng:38503/], count 0
[rospy.internal][INFO] 2021-11-24 16:43:53,282: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-11-24 16:44:24,128: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-11-24 16:44:24,133: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-11-24 16:44:24,133: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-11-24 16:44:24,133: topic[/execution_check] removing connection to http://wng:38503/
[rospy.impl.masterslave][INFO] 2021-11-24 16:44:24,133: signal-2
[rospy.internal][ERROR] 2021-11-24 16:44:24,134: Unable to initiate TCP/IP socket to wng:44169 (http://wng:38503/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-11-24 16:44:24,265: signal_shutdown [atexit]
