[rospy.client][INFO] 2021-12-02 13:06:55,126: init_node, name[/server_endpoint], pid[6380]
[xmlrpc][INFO] 2021-12-02 13:06:55,127: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-02 13:06:55,127: Started XML-RPC server [http://wng:41679/]
[rospy.init][INFO] 2021-12-02 13:06:55,128: ROS Slave URI: [http://wng:41679/]
[rospy.impl.masterslave][INFO] 2021-12-02 13:06:55,128: _ready: http://wng:41679/
[rospy.registration][INFO] 2021-12-02 13:06:55,128: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-12-02 13:06:55,128: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-02 13:06:55,228: registered with master
[rospy.rosout][INFO] 2021-12-02 13:06:55,228: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-02 13:06:55,229: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-02 13:06:55,230: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-02 13:06:55,234: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-02 13:06:55,483: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-02 13:06:58,337: Connection from 192.168.0.8
[rosout][INFO] 2021-12-02 13:06:58,341: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-02 13:06:58,408: topic[/execution_check] adding connection to [http://wng:41679/], count 0
[rospy.internal][INFO] 2021-12-02 13:06:58,410: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-02 13:32:58,822: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-02 13:32:58,827: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-02 13:32:58,827: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-02 13:32:58,827: topic[/execution_check] removing connection to http://wng:41679/
[rospy.impl.masterslave][INFO] 2021-12-02 13:32:58,828: signal-2
[rospy.internal][WARNING] 2021-12-02 13:32:58,828: Unknown error initiating TCP/IP socket to wng:36531 (http://wng:41679/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2021-12-02 13:32:58,943: signal_shutdown [atexit]
