[rospy.client][INFO] 2021-11-26 13:05:44,176: init_node, name[/server_endpoint], pid[20089]
[xmlrpc][INFO] 2021-11-26 13:05:44,176: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-11-26 13:05:44,176: Started XML-RPC server [http://wng:40459/]
[rospy.init][INFO] 2021-11-26 13:05:44,176: ROS Slave URI: [http://wng:40459/]
[rospy.impl.masterslave][INFO] 2021-11-26 13:05:44,176: _ready: http://wng:40459/
[rospy.registration][INFO] 2021-11-26 13:05:44,177: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-11-26 13:05:44,177: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-11-26 13:05:44,277: registered with master
[rospy.rosout][INFO] 2021-11-26 13:05:44,277: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-26 13:05:44,278: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-26 13:05:44,278: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-11-26 13:05:44,282: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-11-26 13:05:44,514: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-11-26 13:05:56,668: Connection from 192.168.1.146
[rosout][INFO] 2021-11-26 13:05:56,673: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-11-26 13:05:56,760: topic[/execution_check] adding connection to [http://wng:40459/], count 0
[rospy.internal][INFO] 2021-11-26 13:05:56,761: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-11-26 13:45:22,181: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-11-26 13:45:22,184: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-11-26 13:45:22,185: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2021-11-26 13:45:22,185: Unable to initiate TCP/IP socket to wng:34487 (http://wng:40459/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2021-11-26 13:45:22,185: topic[/execution_check] removing connection to http://wng:40459/
[rospy.topics][ERROR] 2021-11-26 13:45:22,185: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2021-11-26 13:45:22,186: signal-2
[rospy.core][INFO] 2021-11-26 13:45:22,352: signal_shutdown [atexit]
