[rospy.client][INFO] 2021-11-25 11:02:39,126: init_node, name[/server_endpoint], pid[26249]
[xmlrpc][INFO] 2021-11-25 11:02:39,126: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-11-25 11:02:39,126: Started XML-RPC server [http://wng:36701/]
[rospy.init][INFO] 2021-11-25 11:02:39,126: ROS Slave URI: [http://wng:36701/]
[rospy.impl.masterslave][INFO] 2021-11-25 11:02:39,126: _ready: http://wng:36701/
[xmlrpc][INFO] 2021-11-25 11:02:39,127: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-11-25 11:02:39,126: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-11-25 11:02:39,226: registered with master
[rospy.rosout][INFO] 2021-11-25 11:02:39,227: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-25 11:02:39,227: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-25 11:02:39,228: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-11-25 11:02:39,232: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-11-25 11:02:39,473: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-11-25 11:02:51,354: Connection from 192.168.1.146
[rosout][INFO] 2021-11-25 11:02:51,359: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-11-25 11:02:51,409: topic[/execution_check] adding connection to [http://wng:36701/], count 0
[rospy.internal][INFO] 2021-11-25 11:02:51,410: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-11-25 11:33:51,815: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-11-25 11:33:51,818: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-11-25 11:33:51,819: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2021-11-25 11:33:51,819: Unable to initiate TCP/IP socket to wng:46499 (http://wng:36701/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2021-11-25 11:33:51,819: topic[/execution_check] removing connection to http://wng:36701/
[rospy.impl.masterslave][INFO] 2021-11-25 11:33:51,820: signal-2
[rospy.core][INFO] 2021-11-25 11:33:51,935: signal_shutdown [atexit]
