[rospy.client][INFO] 2021-09-18 16:59:16,881: init_node, name[/server_endpoint], pid[11199]
[xmlrpc][INFO] 2021-09-18 16:59:16,881: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-09-18 16:59:16,881: Started XML-RPC server [http://wng:35029/]
[rospy.init][INFO] 2021-09-18 16:59:16,881: ROS Slave URI: [http://wng:35029/]
[rospy.impl.masterslave][INFO] 2021-09-18 16:59:16,881: _ready: http://wng:35029/
[rospy.registration][INFO] 2021-09-18 16:59:16,882: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-09-18 16:59:16,882: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-09-18 16:59:16,982: registered with master
[rospy.rosout][INFO] 2021-09-18 16:59:16,982: initializing /rosout core topic
[rospy.rosout][INFO] 2021-09-18 16:59:16,984: connected to core topic /rosout
[rospy.simtime][INFO] 2021-09-18 16:59:16,985: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-09-18 16:59:16,992: Starting server on 192.168.1.146:10000
[rospy.internal][INFO] 2021-09-18 16:59:17,241: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-09-18 16:59:52,725: Connection from 192.168.1.146
[rosout][INFO] 2021-09-18 16:59:52,729: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-09-18 16:59:52,776: topic[/execution_check] adding connection to [http://wng:35029/], count 0
[rospy.internal][INFO] 2021-09-18 16:59:52,777: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rosout][ERROR] 2021-09-18 17:11:25,313: Exception: No more data available
[rosout][INFO] 2021-09-18 17:11:25,314: Disconnected from 192.168.1.146
[rospy.core][INFO] 2021-09-18 17:11:28,662: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-09-18 17:11:28,666: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-09-18 17:11:28,667: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-09-18 17:11:28,667: topic[/execution_check] removing connection to http://wng:35029/
[rospy.impl.masterslave][INFO] 2021-09-18 17:11:28,667: signal-2
[rospy.internal][WARNING] 2021-09-18 17:11:28,668: Unknown error initiating TCP/IP socket to wng:39069 (http://wng:35029/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2021-09-18 17:11:29,282: signal_shutdown [atexit]
